AndreFirstMVC/Models/DogViewModel.cs
namespace AndreFirstMVC.Models
{
    public class DogViewModel
    {
        public string Name { get; set; }
        public int Age { get; set; }

    }
}

AndreFirstMVC/Models/ErrorViewModel.cs
namespace AndreFirstMVC.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

AndreFirstMVC/Controllers/HelloWorldController.cs
using Microsoft.AspNetCore.Mvc;
using AndreFirstMVC.Models;

namespace AndreFirstMVC.Controllers
{
    public class HelloWorldController : Controller
    {

        DogViewModel dogForm = null;

        public IActionResult Index(DogViewModel dogForm)
        {
            // DogViewModel AndreDog = new DogViewModel() { Name = "Bruno", Age = 3 };

            // return View(AndreDog);
            return View(dogForm);
        }

        public IActionResult Create()
        {
            return View();
        }

        public string hello()
        { return "Hellow this is Andre!!"; }
    }
}

AndreFirstMVC/Controllers/HomeController.cs
using AndreFirstMVC.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace AndreFirstMVC.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

AndreFirstMVC/Views/HelloWorld/Create.cshtml
@model DogViewModel
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
<h1>Create Dog Page</h1>
<hr />
<div class="row">
    <div class="col-6">
        <div class="card">
            <div class="card-header">Create A New Dog</div>

            <div class="card-body">

            <form asp-controller="HelloWorld" asp-action="Index" method="post">
                <div class="mb-3">
                    <label class="form-label">Dog Name</label>
                    <input asp-for="Name" type="text" class="form-control" />
                </div>
                <div class="mb-3">
                    <label class="form-label">Dog Age</label>
                    <input asp-for="Age" type="number" class="form-control" />
                </div>

                <div class="mb-3">
                    <button type="submit" class="btn btn-primary">Save</button>
                </div>
            </form>

            </div>

            <div class="card-footer"></div>

        </div>

    </div>
</div>

AndreFirstMVC/Views/HelloWorld/Index.cshtml
@model AndreFirstMVC.Models.DogViewModel

@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

<h1>Hello world buddy!!</h1>
<p>Hello Wolrd page</p>

<h4>@Model.Name is @Model.Age years old.</h4>
<h4></h4>

AndreFirstMVC/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

AndreFirstMVC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - AndreFirstMVC</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/AndreFirstMVC.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="HelloWorld" asp-action="Index">AndreFirstMVC</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="HelloWorld" asp-action="Index">Dog List</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="HelloWorld" asp-action="Create">Create Dog</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - AndreFirstMVC - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>